### ISSUE TITLE
EnDocBrowse in OSX

### ISSUE THREAD

**Issue by dubiousdavid** [ensime/ensime-vim#145]
I am unable to get `:EnDocBrowse` to work in OSX. Is there something special I need to do?

**Comment by dubiousdavid** [comment]
Got it working by creating the following bash script named `chrome` and putting it on my path.

```bash
#!/bin/bash

'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' $@
```

**Comment by jvican** [comment]
That's rare. Can you please specify which is your `$BROWSER` variable? It's a good practice to use the full path of your browser, like the one you make reference in your script.
  
I have been fiddling with this in the last days. Another option is using `which` but the problem is Windows doesn't have one and then I would have to implement it in Python (that takes into account several executable details of Windows).
