### ISSUE TITLE
Turn `EnToggle*` commands into settings

### ISSUE THREAD

**Issue by ktonga** [ensime/ensime-vim#290]
I think it isn't worth it to have such kind of commands. I'd rather prefer flag-like settings, they are clearer to set in your `vimrc` if you want always the same behaviour and it is easy enough to script a toggle and assign it a mapping if you change it all the time.

It's just a question. I'd be keen to work on it if you guys agree with me.

**Comment by ches** [comment]
Currently there's only `:EnToggleFullType`, which defaults to shallow types. I would agree that it might make sense to have a `g:` setting for that default, if people want it.

If we ended up with tons of `:EnToggle*` things, yeah that's probably a bit silly, but I think `:EnToggleFullType` is pretty convenient to have built-in. I use `:EnType` dozens of times per day, I'll probably use it and `:EnToggleFullType` even more after #288. It's helpful for libraries and code bases I'm not very familiar with, but I want to switch back when in familiar territory.

I differ in opinion about flags/settings variables overall: Vim users want configurability but I think it's best to try to design the best defaults possible so that people never ask for a setting in the first place. If no one ever asks for something, it probably shouldn't be a setting. They're globals! So of course they suck to maintain 😄  I think it's often better *to have a flexible command/function interface than lots of settings*, like e.g. if we supported `:EnType -qualified` and that's how you use it most of the time, you can make a custom mapping for it, no setting variable needed. That may not be the best example, but you get the idea.

Again just my 2 cents, see what others think!

**Comment by ktonga** [comment]
Well, I saw an [`EnToggleTeardown`](https://github.com/ensime/ensime-vim/blob/master/rplugin/python/ensime.py#L39) also, I've no idea what is it for tho. So it made me think that toggle commands are a standard for the plugin, and I really dislike them.

But I agree that this issue makes more sense if we had many more toggle commands. Do you wanna close it by now?

**Comment by ches** [comment]
Oh I noticed `EnToggleTeardown` today too, it's only defined in Neovim. I didn't grok what it's supposed to do yet either, something about server shutdown… it'd be nice to document it if it should be.

I still think it *is* reasonable to make the default for qualified types a `g:` setting, *maybe*. Could leave this for awhile and see if anyone else has thoughts to add to any of this, up to you.

**Comment by ches** [comment]
And if someone wants to explain `EnToggleTeardown` to us before I have the chance to closely read it, then it could be a good case for your original proposal? Seems like something obscure/maybe mostly for debugging, maybe shouldn't be exposed as a command to users.

**Comment by ches** [comment]
Okay there's nothing actionable here currently, so let's close this. I now understand what `EnToggleTeardown` was supposed to do, and it doesn't work. It'll [go away soon][1] as the proper support for restarting is coming along.

[1]: https://github.com/ensime/ensime-vim/commit/1bdd74c48af870fa193958db195aca0e61b49154

**Comment by ktonga** [comment]
Yeah, I'm ok with that. I've rebased my restart branch on your wip branch and the restart implementation looks a lot cleaner now, but the polling logic is still a mess of global flags, I'll try to clean that up since there is no easy way for leaving the client in a functional state after the associated server is restarted. Let's see what happens.
