### ISSUE TITLE
Support server 2.0

### ISSUE THREAD

**Issue by ktonga** [ensime/ensime-vim#300]
Server 2.0 is starting to diverge from 1.0. It would be nice to support it somehow on the vim plugin side, maybe a separate branch (leaving 1.0 as default branch), so advanced users and contributors can easily switch (configuring the branch in their plugin manager) to start testing/developing the new features/API.

Keep support for both mayor versions in the same branch could lead to a lot of trouble and boilerplate.

**Comment by jvican** [comment]
I completely agree, great idea!

**Comment by ChrisCoffey** [comment]
@ktonga & @jvican I also completely agree. I was chatting with @fommil about this very thing the other day and we agreed a branch is the way to go. I've created the `Server-2.0` branch specifically for this purpose :)

**Comment by ktonga** [comment]
Any idea how to keep both branches in sync? Anything not 2.0 specific should go to `master` and then cherry-picked (adapted if needed) to `server-2.0`

**Comment by ches** [comment]
It's an unfortunate aspect of the Vim plugin ecosystem that users typically run off of `master` (or whatever default repo branch is) because the plugin managers made that much easier than fumbling with the clunky vim.org system—it makes release management a lot harder to achieve.

It's a pain because typical workflow would normally be to keep the latest work that tracks latest server progress on mainline (`master`), with a maintenance branch for 1.0 getting backports, not the other way around.

It *might* be messier, but it could be worth at least considering the possibility of "branching in code" here, i.e. feature flags. This might be a good point at which to undertake some mixin refactoring that's been on the table: define and extract a common interface, then for new features specific to 2.0 or if a response to an existing request message type changes for 2.0, split it out from the common code and mix in the appropriate version-specific parts conditionally based on a setting or automatically at client initialization when the server tells us its version.

Just putting an alternative out there to think about, not sure which is better in the long run. Either way will have some headaches, I'm afraid.

**Comment by jvican** [comment]
Is there any time estimate for the release of 2.0? /cc @fommil

**Comment by ktonga** [comment]
@ches I also thought about that, maintaining both branches could become a nightmare. And it's totally unneeded if the server doesn't diverge too much or if we do something smart on the plugin side to support both protocol versions in the same codebase. Maybe dispatching using typehint + version and doing some common code abstraction on the handlers.

Both approaches seem to be valid and each one with its pros and cons. So I reckon the natural road is to star with __code__ branching and if it gets too messy we always can fallback on __git__ branching.

I can prototype something for #276 that is a trivial diff, a field only present in 2.0

**Comment by jvican** [comment]
To be honest, I wouldn't start by code branching, we need to keep the code as simple as possible. I'm for is working on version 1.0 for the moment being, and whenever the release of 2.0 approaches we'll freeze version 1.0 (leaving it in master), and switch to `server-2.0` (which will be marked as the default branch in the repo so that new contributions are merged only for this version).
  
Given the amount and the importance of changes that 2.0 is gonna bring in, we'd like everyone to use 2.0 as soon as possible. For instance, I'm praying every night so that the graphpocalypse indexer-related issues get merged (see https://github.com/ensime/ensime-server/milestones/Graphpocalypse), since these will improve a lot the user experience of the plugin.

**Comment by fommil** [comment]
2.0 is rolling release, it's out already. But expect the protocol to have breaking changes at times. As for a final release, hunno maybe a year?

**Comment by jvican** [comment]
Okey, in that case code branching sounds good.

**Comment by ktonga** [comment]
Ok, so all good with code branching? I could give #276 a shoot tonight (Aussie time)

**Comment by jvican** [comment]
Yeah, since it seems that there's not more discussion about this topic, go ahead :wink:

**Comment by fommil** [comment]
Emacs just released stable 1.0 so our master in now tracking v2 of the server. There is a pop-up to warn people what to expect, and what is expected of them.

**Comment by ChrisCoffey** [comment]
that's awesome. We're a bit further behind the Emacs feature-set, but once we're closer I'd love to cut a stable release

**Comment by fommil** [comment]
Hehe, calling it "stable" may be a misnomer. Perhaps "something you can return to if everything goes horribly horribly wrong" is more appropriate.
