### ISSUE TITLE
Show type information under selection (not under point)

### ISSUE THREAD

**Issue by sherifkandeel** [ensime/ensime-vim#379]
In `Scala` If there's a line that says:
```
myRepository.getMergeCommitParents(myCommit.id).map(_.map(_.id).toList)
```
The return type `getMergeCommitParents(CommitId)` is a `List[Commit]`
The return type of the whole line is `List[CommitId]`

When I run `EnType` while on `getMergeCommitParents` I get a `List[Commit]` 
There's no way I can run `EnType` on the whole line selection, neither there is a different command that does type information under selection.

You can see what I am referring to in intelliJ by invoking `Alt+ = (Ctrl+ Shift+ P for Mac)`

**Comment by ktonga** [comment]
I agree, this is a handy feature to have.
Currently the implementation is limited to operate with the **word** under the cursor, it totally ignores the current selection. But the good news is that the limitation is on Vim's side, we can fix it and make it work on the selection since the server message already supports offset ranges.

I'll give it a try when I get a chance.

**Comment by sherifkandeel** [comment]
@ktonga That is good news indeed. This one feature is literally the only thing keeping me from using vim + ensime on daily basis at work specially with. I'm thrilled to know it's somehow doable, Thank you!

I am happy to contribute if there's some low hanging tasks that I could do.

**Comment by ktonga** [comment]
We tend to track all outstanding work in issues and make use of labels such as `help wanted` and `low-hanging fruit` take a look and see if there is one you would like to do. Help is always welcome.
